// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EFCore_sample.DbFirst
{
    public partial class EfCoreDbContext : DbContext
    {
        public EfCoreDbContext()
        {
        }

        public EfCoreDbContext(DbContextOptions<EfCoreDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Guild> Guild { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemOption> ItemOption { get; set; }
        public virtual DbSet<ItemReview> ItemReview { get; set; }
        public virtual DbSet<Player> Player { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Item>(entity =>
            {
                entity.HasIndex(e => e.TestCreatorId);

                entity.HasIndex(e => e.TestOwnerId)
                    .IsUnique();

                entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.TestCreator)
                    .WithMany(p => p.ItemTestCreator)
                    .HasForeignKey(d => d.TestCreatorId);

                entity.HasOne(d => d.TestOwner)
                    .WithOne(p => p.ItemTestOwner)
                    .HasForeignKey<Item>(d => d.TestOwnerId);
            });

            modelBuilder.Entity<ItemOption>(entity =>
            {
                entity.HasKey(e => e.ItemId);

                entity.Property(e => e.ItemId).ValueGeneratedNever();

                entity.HasOne(d => d.Item)
                    .WithOne(p => p.ItemOption)
                    .HasForeignKey<ItemOption>(d => d.ItemId);
            });

            modelBuilder.Entity<ItemReview>(entity =>
            {
                entity.HasIndex(e => e.ItemId);

                entity.HasOne(d => d.Item)
                    .WithMany(p => p.ItemReview)
                    .HasForeignKey(d => d.ItemId);
            });

            modelBuilder.Entity<Player>(entity =>
            {
                entity.HasIndex(e => e.GuildId);

                entity.HasIndex(e => e.Name)
                    .HasName("Index_Person_Name")
                    .IsUnique();

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(20);

                entity.HasOne(d => d.Guild)
                    .WithMany(p => p.Player)
                    .HasForeignKey(d => d.GuildId);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}