// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EFCore_sample.DbFirst
{
    public partial class Guild
    {
        public Guild()
        {
            Player = new HashSet<Player>();
        }

        public int GuildId { get; set; }
        public string GuildName { get; set; }

        public virtual ICollection<Player> Player { get; set; }
    }
}