// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EFCore_sample.DbFirst
{
    public partial class ItemReview
    {
        public int ItemReviewId { get; set; }
        public int Score { get; set; }
        public int? ItemId { get; set; }

        public virtual Item Item { get; set; }
    }
}