// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EFCore_sample.DbFirst
{
    public partial class ItemOption
    {
        public int ItemId { get; set; }
        public int Str { get; set; }
        public int Dex { get; set; }
        public int Hp { get; set; }

        public virtual Item Item { get; set; }
    }
}