// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EFCore_sample.DbFirst
{
    public partial class Item
    {
        public Item()
        {
            ItemReview = new HashSet<ItemReview>();
        }

        public int ItemId { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public bool SoftDelete { get; set; }
        public int TemplateId { get; set; }
        public DateTime CreateDate { get; set; }
        public int TestOwnerId { get; set; }
        public int? TestCreatorId { get; set; }
        public DateTime RecoveredDate { get; set; }
        public DateTime? DestroyDate { get; set; }

        public virtual Player TestCreator { get; set; }
        public virtual Player TestOwner { get; set; }
        public virtual ItemOption ItemOption { get; set; }
        public virtual ICollection<ItemReview> ItemReview { get; set; }
    }
}