// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EFCore_sample.DbFirst
{
    public partial class Player
    {
        public Player()
        {
            ItemTestCreator = new HashSet<Item>();
        }

        public int PlayerId { get; set; }
        public string Name { get; set; }
        public int? GuildId { get; set; }

        public virtual Guild Guild { get; set; }
        public virtual Item ItemTestOwner { get; set; }
        public virtual ICollection<Item> ItemTestCreator { get; set; }
    }
}